name: 17 - 2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS
on: 
  workflow_dispatch:

env:
  working-directory: 04-using-actions/react-app

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Check for dependency updates
        uses: ./.github/actions/js-dependancy-update
       